name: datacopilot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - -r backend/requirements.txt
      - -r frontend/requirements.txt
      - -r requirements-dev.txt
