from pathlib import Path


PROJECT_NAME = "DataPilot-AI"
APP_VERSION = "0.1.0"
DEFAULT_PROJECT_ROOT = Path(__file__).resolve().parents[3]

DEFAULT_DATA_DIR = DEFAULT_PROJECT_ROOT / "data"
DEFAULT_CHROMADB_DIR = DEFAULT_DATA_DIR / "chromadb"
DEFAULT_UPLOADS_DIR = DEFAULT_DATA_DIR / "uploads"
DEFAULT_LOGS_DIR = DEFAULT_DATA_DIR / "logs"
DEFAULT_CACHE_DIR = DEFAULT_DATA_DIR / "cache"
DEFAULT_EMBEDDINGS_DIR = DEFAULT_DATA_DIR / "embeddings"
DEFAULT_TEMP_DIR = DEFAULT_DATA_DIR / "temp"
DEFAULT_MODELS_DIR = DEFAULT_PROJECT_ROOT / "models"

ENV_DEVELOPMENT = "development"
ENV_TEST = "test"
ENV_PRODUCTION = "production"

PROVIDER_DEEPSEEK = "deepseek"
PROVIDER_OPENAI = "openai"
PROVIDER_OLLAMA = "ollama"
PROVIDER_LOCAL = "local"

DEFAULT_DEEPSEEK_BASE_URL = "https://api.deepseek.com/v1"
DEFAULT_DEEPSEEK_CHAT_MODEL = "deepseek-chat"
DEFAULT_DEEPSEEK_TIMEOUT_SECONDS = 60

DEFAULT_OPENAI_BASE_URL = "https://api.openai.com/v1"
DEFAULT_OPENAI_CHAT_MODEL = "gpt-4.1-mini"
DEFAULT_OPENAI_TIMEOUT_SECONDS = 60

DEFAULT_OLLAMA_BASE_URL = "http://127.0.0.1:11434"
DEFAULT_OLLAMA_CHAT_MODEL = "qwen3"
DEFAULT_OLLAMA_TIMEOUT_SECONDS = 120

DEFAULT_LOCAL_BASE_URL = "http://127.0.0.1:11434/v1"
DEFAULT_LOCAL_CHAT_MODEL = "datacopilot-qwen3-8b"
DEFAULT_LOCAL_TIMEOUT_SECONDS = 120

DEFAULT_EMBEDDING_MODEL = "BAAI/bge-m3"
